// <auto-generated />
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Onlyspans.Artifact_Storage.Api.Data.Contexts;

#nullable disable

namespace Onlyspans.Artifact_Storage.Api.Migrations
{
    [DbContext(typeof(ArtifactStorageDbContext))]
    partial class ArtifactStorageDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.13")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Onlyspans.Artifact_Storage.Api.Data.Entities.ArtifactEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("ChecksumSha256")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("checksum_sha256");

                    b.Property<string>("ContentType")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("content_type");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Key")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("key");

                    b.Property<Dictionary<string, string>>("Labels")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("labels");

                    b.Property<long>("SizeBytes")
                        .HasColumnType("bigint")
                        .HasColumnName("size_bytes");

                    b.Property<string>("StoragePath")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("storage_path");

                    b.Property<string>("Version")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("version");

                    b.HasKey("Id");

                    b.HasIndex("Key")
                        .HasDatabaseName("ix_artifacts_key_prefix");

                    b.HasIndex("Labels")
                        .HasDatabaseName("ix_artifacts_labels");

                    NpgsqlIndexBuilderExtensions.HasMethod(b.HasIndex("Labels"), "gin");

                    b.HasIndex("Key", "Version")
                        .IsUnique();

                    b.ToTable("artifacts", (string)null);
                });

            modelBuilder.Entity("Onlyspans.Artifact_Storage.Api.Data.Entities.SnapshotArtifactEntity", b =>
                {
                    b.Property<Guid>("SnapshotId")
                        .HasColumnType("uuid")
                        .HasColumnName("snapshot_id");

                    b.Property<Guid>("ArtifactId")
                        .HasColumnType("uuid")
                        .HasColumnName("artifact_id");

                    b.HasKey("SnapshotId", "ArtifactId");

                    b.HasIndex("ArtifactId");

                    b.ToTable("snapshot_artifacts", (string)null);
                });

            modelBuilder.Entity("Onlyspans.Artifact_Storage.Api.Data.Entities.SnapshotEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("ChecksumSha256")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("checksum_sha256");

                    b.Property<string>("ContentType")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("content_type");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Key")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("key");

                    b.Property<Dictionary<string, string>>("Labels")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("labels");

                    b.Property<long>("SizeBytes")
                        .HasColumnType("bigint")
                        .HasColumnName("size_bytes");

                    b.Property<string>("StoragePath")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("storage_path");

                    b.Property<string>("Version")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("version");

                    b.HasKey("Id");

                    b.HasIndex("Key")
                        .HasDatabaseName("ix_snapshots_key_prefix");

                    b.HasIndex("Labels")
                        .HasDatabaseName("ix_snapshots_labels");

                    NpgsqlIndexBuilderExtensions.HasMethod(b.HasIndex("Labels"), "gin");

                    b.HasIndex("Key", "Version")
                        .IsUnique();

                    b.ToTable("snapshots", (string)null);
                });

            modelBuilder.Entity("Onlyspans.Artifact_Storage.Api.Data.Entities.SnapshotArtifactEntity", b =>
                {
                    b.HasOne("Onlyspans.Artifact_Storage.Api.Data.Entities.ArtifactEntity", "Artifact")
                        .WithMany("SnapshotArtifacts")
                        .HasForeignKey("ArtifactId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Onlyspans.Artifact_Storage.Api.Data.Entities.SnapshotEntity", "Snapshot")
                        .WithMany("SnapshotArtifacts")
                        .HasForeignKey("SnapshotId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Artifact");

                    b.Navigation("Snapshot");
                });

            modelBuilder.Entity("Onlyspans.Artifact_Storage.Api.Data.Entities.ArtifactEntity", b =>
                {
                    b.Navigation("SnapshotArtifacts");
                });

            modelBuilder.Entity("Onlyspans.Artifact_Storage.Api.Data.Entities.SnapshotEntity", b =>
                {
                    b.Navigation("SnapshotArtifacts");
                });
#pragma warning restore 612, 618
        }
    }
}
